// packages/uses/react/src/App.tsx
import { MyComponent, MyTest } from "@stencil-test/react";

function App() {
	return (
		<>
			<MyComponent
				first="React"
				onMyChange={() => {
					console.log("React Trigger");
				}}
				style={{
					color: "red",
				}}
			></MyComponent>

			<MyTest>
				<p>123</p>
			</MyTest>
		</>
	);
}

export default App;

// packages/uses/vue3/src/App.vue
<script setup lang="ts">
import { MyComponent, MyTest } from "@stencil-test/vue3";

const handleChange = () => {
	console.log("change");
};
</script>

<template>
	<MyComponent first="Stencil" class="test" />
	<MyComponent first="Stencil" style="color: red" />
	<MyComponent first="my-change" @my-change="handleChange" />
	<MyComponent first="myChange" @myChange="handleChange" />

	<MyComponent>
		<MyTest slot="test" />
	</MyComponent>

	<my-component>
		<my-test slot="test" />
	</my-component>
</template>
