// packages/uses/react/src/App.tsx
import { MyComponent, MyTest } from "@stencil-test/react";

function App() {
	return (
		<>
			<MyComponent
				first="React"
				onMyChange={() => {
					console.log("React Trigger");
				}}
				style={{
					color: "red",
				}}
			></MyComponent>

			<MyTest>
				<p>123</p>
			</MyTest>
		</>
	);
}

export default App;

// packages/uses/vue2/src/App.vue
<script setup lang="ts">
import { MyComponent } from "@stencil-test/vue2";

const handleChange = () => {
	console.log("change");
};
</script>

<template>
	<div>
		<MyComponent first="my-change" @my-change="handleChange" />
		<MyComponent first="myChange" @myChange="handleChange" />
	</div>
</template>
